### PR TITLE
us completed

### PR DESCRIPTION
**Pull request by mustafamuezzinoglu**
eventually

### CODE REVIEW

**Review by Makaraoglan — CHANGES_REQUESTED** [review]
reuseful methods should be in pages class

**Comment by mustafamuezzinoglu** [comment]
ok

**Review by Makaraoglan — CHANGES_REQUESTED** [review]
review

**Comment by mustafamuezzinoglu** [comment]
ok

**Comment by mustafamuezzinoglu** [comment]
tmm

**Review by Makaraoglan — APPROVED** [review]
ok

**Comment by mustafamuezzinoglu** [comment]
thanks a lot

**Pull request merged**
